---
title: "Reference choice"
author: "Chenyu Li"
format: html
editor: source
editor_options: 
  chunk_output_type: console
---

# 1 Initial setting

## 1.1 Clear workspace and set default colors

```{r reset, include=FALSE}
# Clear all plots and variables from workspace
graphics.off()
rm(list=ls(all.names=TRUE))

# Set numerical precision and color schemes
options(digits = 3)
options(ggplot2.discrete.colour= c("#615F63","#FF7F6F","#2F7FC1","#FFBE7A"))
options(ggplot2.discrete.fill= c("#615F63","#FF7F6F","#2F7FC1","#FFBE7A"))
```

## 1.2 Import functions and packages

```{r}
# Install and load required packages
packages = c(
  # CRAN packages for data analysis and visualization
  "tidyverse", "brms", "bmm", "ggpubr", "tidybayes", "emmeans", "bayestestR",
  # Github packages for specialized functions
  "chenyu-psy/smartr@v0.3.2"
)
process_packages(packages, quietly = TRUE)

# Source all local R functions from the functions directory
# load_functions("./functions")

# Set default ggplot theme
theme_set(theme_bw())

# Define position dodge constants for plotting
dodge1 = position_dodge(.1)
dodge2 = position_dodge(.2)

```

# Import data

```{r}

Data = read_csv("./raw_data/image_analysis_results.csv")

ref_size = 16
ratio = 2

Data_ref_objects <- Data %>% 
  filter(size == ref_size)

Data_good_objects <- Data %>% 
  filter(
    (size > ref_size & size < ref_size * ratio * 2) | (size < ref_size & size > ref_size/ratio/2)
  )

print(nrow(Data_good_objects))

```

